# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Prosecutor
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ProsecutorMSP

        # ID to load the MSP definition as
        ID: ProsecutorMSP

        MSPDir: ../organizations/peerOrganizations/prosecutor.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ProsecutorMSP.admin', 'ProsecutorMSP.peer', 'ProsecutorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ProsecutorMSP.admin', 'ProsecutorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ProsecutorMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ProsecutorMSP.peer')"
