#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: collectingofficer-peer1-tls-cert
  namespace: ${COLLECTINGOFFICER_NS}
spec:
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - localhost
    - collectingofficer-peer1
    - collectingofficer-peer1.${COLLECTINGOFFICER_NS}.svc.cluster.local
    - collectingofficer-peer1.${DOMAIN}
    - collectingofficer-peer-gateway-svc
    - collectingofficer-peer-gateway-svc.${DOMAIN}
  ipAddresses:
    - 127.0.0.1
  secretName: collectingofficer-peer1-tls-cert
  issuerRef:
    name: collectingofficer-tls-cert-issuer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collectingofficer-peer1-config
data:
  FABRIC_CFG_PATH: /var/hyperledger/fabric/config
  FABRIC_LOGGING_SPEC: "debug:cauthdsl,policies,msp,grpc,peer.gossip.mcs,gossip,leveldbhelper=info"
  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_TLS_CERT_FILE: /var/hyperledger/fabric/config/tls/tls.crt
  CORE_PEER_TLS_KEY_FILE: /var/hyperledger/fabric/config/tls/tls.key
  CORE_PEER_TLS_ROOTCERT_FILE: /var/hyperledger/fabric/config/tls/ca.crt
  CORE_PEER_ID: collectingofficer-peer1.collectingofficer.example.com
  CORE_PEER_ADDRESS: collectingofficer-peer1:7051
  CORE_PEER_LISTENADDRESS: 0.0.0.0:7051
  CORE_PEER_CHAINCODEADDRESS: collectingofficer-peer1:7052
  CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
  # bootstrap peer is the other peer in the same org
  CORE_PEER_GOSSIP_BOOTSTRAP: collectingofficer-peer2:7051
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: collectingofficer-peer1.${COLLECTINGOFFICER_NS}.svc.cluster.local:7051
  CORE_PEER_LOCALMSPID: CollectingOfficerMSP
  CORE_PEER_MSPCONFIGPATH: /var/hyperledger/fabric/organizations/peerOrganizations/collectingofficer.example.com/peers/collectingofficer-peer1.collectingofficer.example.com/msp
  CORE_OPERATIONS_LISTENADDRESS: 0.0.0.0:9443
  CORE_PEER_FILESYSTEMPATH: /var/hyperledger/fabric/data/collectingofficer-peer1.collectingofficer.example.com
  CORE_LEDGER_SNAPSHOTS_ROOTDIR: /var/hyperledger/fabric/data/collectingofficer-peer1.collectingofficer.example.com/snapshots
  CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG: "{\"peername\":\"collectingofficerpeer1\"}"
  FABRIC_K8S_BUILDER_OBJECT_NAME_PREFIX: collectingofficer-peer1-cc
  CORE_LEDGER_STATE_STATEDATABASE: CouchDB
  CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIESONSTARTUP: "20"
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: localhost:5984
  CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: admin
  CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: adminpw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collectingofficer-peer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collectingofficer-peer1
  template:
    metadata:
      labels:
        app: collectingofficer-peer1
        org: collectingofficer
    spec:
      containers:
        - name: main
          image: ${FABRIC_PEER_IMAGE}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: collectingofficer-peer1-config
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 9443
          volumeMounts:
            - name: fabric-volume
              mountPath: /var/hyperledger
            - name: fabric-config
              mountPath: /var/hyperledger/fabric/config
            - name: tls-cert-volume
              mountPath: /var/hyperledger/fabric/config/tls
              readOnly: true
        - name: couchdb
          image: couchdb:${COUCHDB_VERSION}
          imagePullPolicy: IfNotPresent
          env:
            - name: "COUCHDB_USER"
              value: "admin" 
            - name: "COUCHDB_PASSWORD"
              value: "adminpw"
          ports:
              - containerPort: 5984
      volumes:
        - name: fabric-volume
          persistentVolumeClaim:
            claimName: fabric-collectingofficer
        - name: fabric-config
          configMap:
            name: collectingofficer-config
        - name: tls-cert-volume
          secret:
            secretName: collectingofficer-peer1-tls-cert
---
apiVersion: v1
kind: Service
metadata:
  name: collectingofficer-peer1
spec:
  ports:
    - name: grpc
      port: 7051
      protocol: TCP
    - name: chaincode
      port: 7052
      protocol: TCP
    - name: operations
      port: 9443
      protocol: TCP
  selector:
    app: collectingofficer-peer1
---
apiVersion: v1
kind: Service
metadata:
  name: collectingofficer-peer-gateway-svc
spec:
  ports:
    - name: grpc
      port: 7051
      protocol: TCP
  selector:
    org: collectingofficer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    app: collectingofficer-peer1
  name: collectingofficer-peer1
spec:
  ingressClassName: nginx
  rules:
    - host: collectingofficer-peer1.${DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: collectingofficer-peer1
                port:
                  name: grpc
            path: /
            pathType: ImplementationSpecific
    - host: collectingofficer-peer-gateway-svc.${DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: collectingofficer-peer-gateway-svc
                port:
                  name: grpc
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - collectingofficer-peer1.${DOMAIN}
    - hosts:
        - collectingofficer-peer-gateway-svc.${DOMAIN}
