---
Organizations:

  - &CollectingOfficerOrg
    Name: CollectingOfficerOrgMSP
    ID: CollectingOfficerOrgMSP
    MSPDir: ../organizations/peerOrganizations/collectingofficer.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('CollectingOfficerOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('CollectingOfficerOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('CollectingOfficerOrgMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('CollectingOfficerOrgMSP.peer')"
    AnchorPeers:
      - Host: peer0.collectingofficer.example.com
        Port: 7051

  - &EvidenceCustodianOrg
    Name: EvidenceCustodianOrgMSP
    ID: EvidenceCustodianOrgMSP
    MSPDir: ../organizations/peerOrganizations/evidencecustodian.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('EvidenceCustodianOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('EvidenceCustodianOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('EvidenceCustodianOrgMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('EvidenceCustodianOrgMSP.peer')"
    AnchorPeers:
      - Host: peer0.evidencecustodian.example.com
        Port: 7051

  - &ForensicAnalystOrg
    Name: ForensicAnalystOrgMSP
    ID: ForensicAnalystOrgMSP
    MSPDir: ../organizations/peerOrganizations/forensicanalyst.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ForensicAnalystOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ForensicAnalystOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ForensicAnalystOrgMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ForensicAnalystOrgMSP.peer')"
    AnchorPeers:
      - Host: peer0.forensicanalyst.example.com
        Port: 7051

  - &ProsecutorOrg
    Name: ProsecutorOrgMSP
    ID: ProsecutorOrgMSP
    MSPDir: ../organizations/peerOrganizations/prosecutor.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ProsecutorOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ProsecutorOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ProsecutorOrgMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ProsecutorOrgMSP.peer')"
    AnchorPeers:
      - Host: peer0.prosecutor.example.com
        Port: 7051

  - &CourtroomPersonnelOrg
    Name: CourtroomPersonnelOrgMSP
    ID: CourtroomPersonnelOrgMSP
    MSPDir: ../organizations/peerOrganizations/courtroom.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('CourtroomPersonnelOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('CourtroomPersonnelOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('CourtroomPersonnelOrgMSP.admin')"

  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererOrgMSP
    MSPDir: ../organizations/ordererOrganizations/orderer.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererOrgMSP.admin')"

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer1.orderer.example.com:7050
    - orderer2.orderer.example.com:8050
    - orderer3.orderer.example.com:9050

  EtcdRaft:
    Consenters:
      - Host: orderer1.orderer.example.com
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/orderer.example.com/orderers/orderer1.orderer.example.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/orderer.example.com/orderers/orderer1.orderer.example.com/tls/server.crt

      - Host: orderer2.orderer.example.com
        Port: 8050
        ClientTLSCert: ../organizations/ordererOrganizations/orderer.example.com/orderers/orderer2.orderer.example.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/orderer.example.com/orderers/orderer2.orderer.example.com/tls/server.crt

      - Host: orderer3.orderer.example.com
        Port: 9050
        ClientTLSCert: ../organizations/ordererOrganizations/orderer.example.com/orderers/orderer3.orderer.example.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/orderer.example.com/orderers/orderer3.orderer.example.com/tls/server.crt

  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

  Capabilities:
    V2_0: true

Application: &ApplicationDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

  Capabilities:
    V2_0: true

  Organizations:

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    V2_0: true

Profiles:

  LawSystemGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *CollectingOfficerOrg
          - *EvidenceCustodianOrg
          - *ForensicAnalystOrg
          - *ProsecutorOrg
          - *CourtroomPersonnelOrg

  LawChannel:
    <<: *ChannelDefaults
    Consortium: SampleConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *CollectingOfficerOrg
        - *EvidenceCustodianOrg
        - *ForensicAnalystOrg
        - *ProsecutorOrg
        - *CourtroomPersonnelOrg
